spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysite_db?characterEncoding=utf-8&useSSL=false
    username: root
    password: hedixuan..5253979
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error